name: Build Folcolor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Build Release
      run: |
        msbuild src/Controller/Controller.sln /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v143
        
    - name: Check build output
      run: |
        if (Test-Path "src/Controller/Win32/Release/Folcolor.exe") {
          Write-Host "✅ Build successful - Folcolor.exe created"
          Get-ChildItem "src/Controller/Win32/Release/Folcolor.exe" | Format-List Name, Length, LastWriteTime
        } else {
          Write-Host "❌ Build failed - Folcolor.exe not found"
          Write-Host "Checking available files in output directory:"
          Get-ChildItem "src/Controller" -Recurse -Name "*.exe" -ErrorAction SilentlyContinue
          Write-Host "Checking all directories:"
          Get-ChildItem "src/Controller" -Directory | ForEach-Object { Write-Host $_.Name }
          exit 1
        }
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Folcolor-exe
        path: src/Controller/Win32/Release/Folcolor.exe
        retention-days: 7